### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by Katan5555** [mims-harvard/PrimeKG#3]
Hello, 
Thanks for creating this great knowledge graph, while I was able to use it with PyKEEN, I would like now to learn to build it from scratch. Are the input files already available somewhere or should I download them in each of their websites ? I only see the processing script. 
Thanks ! 
Mi

**Comment by payalchandak** [comment]
Hi, 

We are glad that PrimeKG was a useful resource for you. Unfortunately we cannot provide processed input files on the web since we would be duplicating other copyrighted databases. Please keep an eye out for a publication soon to appear in Nature Scientific Data that will provide links and details to all the primary data resources. Then you can download them yourself and use these processing scripts to clean up the input files. 

Hope this helps! 

Best, 
Payal
